### ISSUE TITLE
12c install cleanup: Lots of error messages...

### ISSUE THREAD

**Issue by mkoertgen** [wkoertgen/train.oracle12.migration#1]
The cleanup command in [oracle12c-install.sh#L42](https://github.com/wkoertgen/train.oracle12.migration/blob/master/scripts/oracle12c-install.sh#L42) causes many error messages on screen, like this

```
==> default: rm: cannot remove ???/vagrant/12c_installer/database/stage/Components/oracle.ldap.client/12.1.0.2.0/1???: Directory not empty
...
```

**Comment by mkoertgen** [comment]
Might be a user issue (mounted by vagrant, executed by ?). Maybe this occurs on Windows only. Anyway, messages could be supressed.

**Comment by wkoertgen** [comment]
mail to Constantin written: we need to know on which system this occurs. Nevertheless I will try to direct the output to /dev/null

**Comment by rbrn** [comment]
I can confirm it works correctly on ubuntu. One thing I had to do is modify the /etc/hosts adding the new hostname before running vagrant provision because vagrant up failed initially as the installer is doing some sort of integrity checks. Also you have to install both 11g and 12c otherwise you will have to customize it. Thanks for creating this project. Really helpful.

**Comment by wkoertgen** [comment]
Thank you, Constantin. Can you tell us, in which way you had to modify 
the /etc/hosts ?

Am 04.05.2015 um 21:27 schrieb Constantin Aldea:

> I can confirm it works correctly on ubuntu. One thing I had to do is 
> modify the /etc/hosts before running vagrant provision as the 
> installer is doing some sort of integrity checks. Also you have to 
> install both 11g and 12c otherwise you will have to customize it
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wkoertgen/train.oracle12.migration/issues/1#issuecomment-98824940.

## 

Freundliche Grüsse / Kind Regards

Hans Werner Körtgen
DBLAB Körtgen
Sülzgürtel 86
D-50937 K ö l n

DEUTSCHLAND / GERMANY

Mobile: +49 162 6272476 (NEU !)
Site: www.koertgen.de

**Comment by rbrn** [comment]
Had to enter the vagrant guest(vagrant ssh) amd add oracle12c.localdomain to /etc/hosts,  went out of the guest and 'vagrant provision' and it worked fine. This by the state of the project on last friday. Don't know how things changed in the meantime. TA

**Comment by wkoertgen** [comment]
Thanks Constantin.

We have thought to invite you as contributor. What do you think?

Keep in mind, that I am member of DOAG (German Oracle User Group) and 
that they know meanwhile, what my son and I are doing there. This does 
not always please everybody.

I set my son to CC.

On 05.05.2015 10:27, Constantin Aldea wrote:

> Had to enter the vagrant guest(vagrant ssh) amd add 
> oracle12c.localdomain to /etc/hosts, went out of the guest and 
> 'vagrant provision' and it worked fine. This by the state of the 
> project on last friday. Don't know how things changed in the meantime. TA
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wkoertgen/train.oracle12.migration/issues/1#issuecomment-98991811.

## 

Freundliche Grüsse / Kind Regards

Hans Werner Körtgen
DBLAB Körtgen
Sülzgürtel 86
D-50937 Köln / Cologne

DEUTSCHLAND / GERMANY

Mobile: +49 162 6272476 (NEW !)
Site: www.koertgen.de

**Comment by rbrn** [comment]
Hi, would be glad to help if I can. 
Const

**Comment by wkoertgen** [comment]
you are welcome, I have added you as collaborator. I will tell my son - 
we are going to hear a concert in Cologne in an hour.

On 06.05.2015 12:55, Constantin Aldea wrote:

> Hi, would be glad to help if I can.
> Const
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wkoertgen/train.oracle12.migration/issues/1#issuecomment-99417293.

## 

Freundliche Grüsse / Kind Regards

Hans Werner Körtgen
DBLAB Körtgen
Sülzgürtel 86
D-50937 Köln / Cologne

DEUTSCHLAND / GERMANY

Mobile: +49 162 6272476 (NEW !)
Site: www.koertgen.de
