### ISSUE TITLE
oracle11g logfile grows quite large

### ISSUE THREAD

**Issue by mkoertgen** [wkoertgen/train.oracle12.migration#2]
I have the ora11g-logfile 20MB and growing... Is this intended? Is this ok?

**Comment by wkoertgen** [comment]
There are 2 ways:
a) lead the output of /dev/null 
b) zip it as klast step of the install.

During the development I needed the clear output. Meanwhile it runs stable. No problem to thow it to garbage.

I suggest, to open question in the FAQ and leave it to the user to decide: he cacontrol the setup.
