### ISSUE TITLE
package base box

### ISSUE THREAD

**Issue by mkoertgen** [wkoertgen/train.oracle12.migration#3]
This should be a good resource: http://www.automatedtrader.net/blogs/oracle/145081/shrinking-a-linux-oel-6-virtual-box-image-vdi-hosted-on-windows--7

**Comment by mkoertgen** [comment]
Also good: http://sbin.blogspot.de/2011/02/how-to-shink-or-compact-virtual-disk.html

**Comment by mkoertgen** [comment]
Ok, could not get zerofree installed on oel71. As suggested in blogpost [How to shink or compact a virtual disk](http://sbin.blogspot.de/2011/02/how-to-shink-or-compact-virtual-disk.html) i tried the most recent zerofree rpm package with

```
 sudo rpm-ivh ftp://ftp.pbone.net/mirror/archive.fedoraproject.org/fedora/linux/releases/15/Fedora/i386/os/Packages/zerofree-1.0.1-8.fc15.i686.rpm
```

but it failed to get the dependencies

```
Retrieving ftp://ftp.pbone.net/mirror/archive.fedoraproject.org/fedora/linux/releases/15/Fedora/i386/os/Packages/zerofree-1.0.1-8.fc15.i686.rpm
warning: /var/tmp/rpm-tmp.LlqcvE: Header V3 RSA/SHA256 Signature, key ID 069c8460: NOKEY
error: Failed dependencies:
        libc.so.6 is needed by zerofree-1.0.1-8.fc15.i686
        libc.so.6(GLIBC_2.0) is needed by zerofree-1.0.1-8.fc15.i686
        libc.so.6(GLIBC_2.3.4) is needed by zerofree-1.0.1-8.fc15.i686
        libext2fs.so.2 is needed by zerofree-1.0.1-8.fc15.i686
```

**Comment by wkoertgen** [comment]
The VirtualBox used to have 17GB uncompressed and 7GB compressed. I have optimized the setup process - less optionsw & storage for the Container Database - applied /dev/zero: The actual Box now has 13,6GB uncompressed , 5,47 GB compressed. This is a partial success. 
I will try to get a higher compress rate.
Meanwhile I suggest to tag the actual release and to commit the new setup process later.

**Comment by mkoertgen** [comment]
Ok, should be enough for now.
